/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.SetImagen;
import controlador.juego.AccesLabels;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLabel;

/**
 *
 * @author PC1
 */
public class Juego extends javax.swing.JFrame {

    private final SetImagen SET_IMAGE = new SetImagen(this);
    private final String URL_ICONO = "vista/images/icono.png";
    private final AccesLabels accesLabels = new AccesLabels(this);
    
    public Juego() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //this.lblNombreUsuario.setText(Principal.getInfoJugador().getNombreUsuario());
        this.accesLabels.setLabels();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource(URL_ICONO));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupobtnOpciones = new javax.swing.ButtonGroup();
        pnlJuego = new javax.swing.JPanel();
        lblPreguntaContenido = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        rbtnOpcion1 = new javax.swing.JRadioButton();
        rbtnOpcion2 = new javax.swing.JRadioButton();
        rbtnOpcion3 = new javax.swing.JRadioButton();
        rbtnOpcion4 = new javax.swing.JRadioButton();
        lblCategoria = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUIZ!");
        setBackground(new java.awt.Color(255, 255, 255));

        pnlJuego.setBackground(new java.awt.Color(255, 255, 255));

        lblPreguntaContenido.setText("Contenido de la pregunta");

        lblNombreUsuario.setText("Nombre de usuario");

        lblCerrarSesion.setText("Cerrar Sesion");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        grupobtnOpciones.add(rbtnOpcion1);
        rbtnOpcion1.setText("Opcion 1");
        rbtnOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOpcion1ActionPerformed(evt);
            }
        });

        grupobtnOpciones.add(rbtnOpcion2);
        rbtnOpcion2.setText("Opcion 2");

        grupobtnOpciones.add(rbtnOpcion3);
        rbtnOpcion3.setText("Opcion 3");
        rbtnOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOpcion3ActionPerformed(evt);
            }
        });

        grupobtnOpciones.add(rbtnOpcion4);
        rbtnOpcion4.setText("Opcion 4");

        lblCategoria.setText("Categoria");

        lblNivel.setText("Nivel");

        lblPuntos.setText("Puntos");

        javax.swing.GroupLayout pnlJuegoLayout = new javax.swing.GroupLayout(pnlJuego);
        pnlJuego.setLayout(pnlJuegoLayout);
        pnlJuegoLayout.setHorizontalGroup(
            pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJuegoLayout.createSequentialGroup()
                .addGroup(pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlJuegoLayout.createSequentialGroup()
                        .addGroup(pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlJuegoLayout.createSequentialGroup()
                                .addGap(331, 331, 331)
                                .addComponent(lblCategoria))
                            .addGroup(pnlJuegoLayout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addGroup(pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnOpcion4)
                                    .addComponent(rbtnOpcion3)
                                    .addComponent(rbtnOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnOpcion2)))
                            .addGroup(pnlJuegoLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(lblPreguntaContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 217, Short.MAX_VALUE))
                    .addGroup(pnlJuegoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuntos)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJuegoLayout.createSequentialGroup()
                                .addComponent(lblNivel)
                                .addGap(137, 137, 137)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCerrarSesion)
                            .addComponent(lblNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnlJuegoLayout.setVerticalGroup(
            pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJuegoLayout.createSequentialGroup()
                .addGroup(pnlJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJuegoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(60, 60, 60)
                        .addComponent(lblCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(lblPreguntaContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(rbtnOpcion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnOpcion2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnOpcion3)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnOpcion4))
                    .addGroup(pnlJuegoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCerrarSesion)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOpcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnOpcion1ActionPerformed

    private void rbtnOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOpcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnOpcion3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }
    
    //Getters & Setters
    
    public JLabel getLblCategoria() {
        return lblPuntos;
    }

    public void setLblCategoria(JLabel lblCategoria) {
        this.lblPuntos = lblCategoria;
    }

    public JLabel getLblNivel() {
        return lblNivel;
    }

    public void setLblNivel(JLabel lblNivel) {
        this.lblNivel = lblNivel;
    }

    public JLabel getLblNombreUsuario() {
        return lblNombreUsuario;
    }

    public void setLblNombreUsuario(JLabel lblNombreUsuario) {
        this.lblNombreUsuario = lblNombreUsuario;
    }

    public JLabel getLblPreguntaContenido() {
        return lblPreguntaContenido;
    }

    public void setLblPreguntaContenido(JLabel lblPreguntaContenido) {
        this.lblPreguntaContenido = lblPreguntaContenido;
    }

    public JLabel getLblPuntos() {
        return lblPuntos;
    }

    public void setLblPuntos(JLabel lblPuntos) {
        this.lblPuntos = lblPuntos;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupobtnOpciones;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPreguntaContenido;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JPanel pnlJuego;
    private javax.swing.JRadioButton rbtnOpcion1;
    private javax.swing.JRadioButton rbtnOpcion2;
    private javax.swing.JRadioButton rbtnOpcion3;
    private javax.swing.JRadioButton rbtnOpcion4;
    // End of variables declaration//GEN-END:variables
}
