/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.SetImagen;
import controlador.juego.JuegoControl;
import controlador.juego.JuegoInfo;
import controlador.juego.actionperfomer.ActionPerformerAbstract;
import controlador.juego.actionperfomer.BotonAceptar;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.SwingConstants;

public class Juego extends javax.swing.JFrame {

    private final SetImagen SET_IMAGE = new SetImagen(this);
    private final String URL_ICONO = "vista/images/icono.png";
    private final JuegoInfo juegoInfo = new JuegoInfo(this);
    private ActionPerformerAbstract action;
    
    public Juego() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.juegoInfo.showInfo();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource(URL_ICONO));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupobtnOpciones = new javax.swing.ButtonGroup();
        pnlJuego = new javax.swing.JPanel();
        lblPreguntaContenido = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        rbtnOpcion1 = new javax.swing.JRadioButton();
        rbtnOpcion2 = new javax.swing.JRadioButton();
        rbtnOpcion3 = new javax.swing.JRadioButton();
        rbtnOpcion4 = new javax.swing.JRadioButton();
        lblCategoria = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        lblPuntosAcumulados = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUIZ!");
        setBackground(new java.awt.Color(255, 255, 255));

        pnlJuego.setBackground(new java.awt.Color(255, 255, 255));
        pnlJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPreguntaContenido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPreguntaContenido.setText("Contenido de la pregunta");
        lblPreguntaContenido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 0), new java.awt.Color(204, 153, 0)));
        lblPreguntaContenido.setHorizontalAlignment(SwingConstants.CENTER);
        lblPreguntaContenido.setVerticalAlignment(SwingConstants.CENTER);
        pnlJuego.add(lblPreguntaContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 128, 422, 117));

        lblNombreUsuario.setText("Nombre de usuario");
        pnlJuego.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        lblCerrarSesion.setText("Cerrar Sesion");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });
        pnlJuego.add(lblCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        grupobtnOpciones.add(rbtnOpcion1);
        rbtnOpcion1.setText("Opcion 1");
        rbtnOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOpcion1ActionPerformed(evt);
            }
        });
        pnlJuego.add(rbtnOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 290, 106, -1));

        grupobtnOpciones.add(rbtnOpcion2);
        rbtnOpcion2.setText("Opcion 2");
        pnlJuego.add(rbtnOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 323, -1, -1));

        grupobtnOpciones.add(rbtnOpcion3);
        rbtnOpcion3.setText("Opcion 3");
        rbtnOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOpcion3ActionPerformed(evt);
            }
        });
        pnlJuego.add(rbtnOpcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 356, -1, -1));

        grupobtnOpciones.add(rbtnOpcion4);
        rbtnOpcion4.setText("Opcion 4");
        pnlJuego.add(rbtnOpcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 395, -1, -1));

        lblCategoria.setText("Categoria");
        pnlJuego.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 94, -1, -1));

        lblNivel.setText("Nivel");
        pnlJuego.add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 42, -1, -1));

        lblPuntos.setText("Puntos");
        pnlJuego.add(lblPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 64, -1, -1));

        lblPuntosAcumulados.setText("Puntos acumulados");
        pnlJuego.add(lblPuntosAcumulados, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 14, -1, -1));

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnlJuego.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 443, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/quizLogo.png"))); // NOI18N
        pnlJuego.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 590, 310));
        pnlJuego.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        this.action = new BotonAceptar(this, evt);

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void rbtnOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOpcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnOpcion3ActionPerformed

    private void rbtnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOpcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnOpcion1ActionPerformed

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked

        JuegoControl juegoControl = new JuegoControl(this);
        juegoControl.salirYGuardar();

    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }
    
    //Getters & Setters

    public JLabel getLblCategoria() {
        return lblCategoria;
    }

    public void setLblCategoria(JLabel lblCategoria) {
        this.lblCategoria = lblCategoria;
    }
    
    

    public JLabel getLblNivel() {
        return lblNivel;
    }

    public void setLblNivel(JLabel lblNivel) {
        this.lblNivel = lblNivel;
    }

    public JLabel getLblNombreUsuario() {
        return lblNombreUsuario;
    }

    public void setLblNombreUsuario(JLabel lblNombreUsuario) {
        this.lblNombreUsuario = lblNombreUsuario;
    }

    public JLabel getLblPreguntaContenido() {
        return lblPreguntaContenido;
    }

    public void setLblPreguntaContenido(JLabel lblPreguntaContenido) {
        this.lblPreguntaContenido = lblPreguntaContenido;
    }

    public JLabel getLblPuntos() {
        return lblPuntos;
    }

    public void setLblPuntos(JLabel lblPuntos) {
        this.lblPuntos = lblPuntos;
    }

    public JLabel getLblPuntosAcumulados() {
        return lblPuntosAcumulados;
    }

    public void setLblPuntosAcumulados(JLabel lblPuntosAcumulados) {
        this.lblPuntosAcumulados = lblPuntosAcumulados;
    }

    public JRadioButton getRbtnOpcion1() {
        return rbtnOpcion1;
    }

    public void setRbtnOpcion1(JRadioButton rbtnOpcion1) {
        this.rbtnOpcion1 = rbtnOpcion1;
    }

    public JRadioButton getRbtnOpcion2() {
        return rbtnOpcion2;
    }

    public void setRbtnOpcion2(JRadioButton rbtnOpcion2) {
        this.rbtnOpcion2 = rbtnOpcion2;
    }

    public JRadioButton getRbtnOpcion3() {
        return rbtnOpcion3;
    }

    public void setRbtnOpcion3(JRadioButton rbtnOpcion3) {
        this.rbtnOpcion3 = rbtnOpcion3;
    }

    public JRadioButton getRbtnOpcion4() {
        return rbtnOpcion4;
    }

    public void setRbtnOpcion4(JRadioButton rbtnOpcion4) {
        this.rbtnOpcion4 = rbtnOpcion4;
    }

    public ButtonGroup getGrupobtnOpciones() {
        return grupobtnOpciones;
    }

    public void setGrupobtnOpciones(ButtonGroup grupobtnOpciones) {
        this.grupobtnOpciones = grupobtnOpciones;
    }
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.ButtonGroup grupobtnOpciones;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPreguntaContenido;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblPuntosAcumulados;
    private javax.swing.JPanel pnlJuego;
    private javax.swing.JRadioButton rbtnOpcion1;
    private javax.swing.JRadioButton rbtnOpcion2;
    private javax.swing.JRadioButton rbtnOpcion3;
    private javax.swing.JRadioButton rbtnOpcion4;
    // End of variables declaration//GEN-END:variables
}
