/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.SetImagen;
import java.awt.Image;
import java.awt.Toolkit;
import modelo.negocio.UsuarioControl;
import modelo.transferobject.AdminDto;
import modelo.transferobject.JugadorDto;
import modelo.transferobject.UsuarioDto;

/**
 *
 * @author PC1
 */
public class Principal extends javax.swing.JFrame {
    
    private static JugadorDto infoJugador;
    private static AdminDto infoAdmin;
    private final SetImagen setImagen = new SetImagen(this);
    private final String URL_QUIZLOGO = "src/vista/images/quizLogo.png";
    private final String URL_ICONO = "vista/images/icono.png";

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setImagen.ajustarImagenLabel(lblLogoQuiz, URL_QUIZLOGO);
    }

   @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource(URL_ICONO));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        lblLogoQuiz = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblAunNoTieneCuenta = new javax.swing.JLabel();
        lblRegistrarse = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        lblWarning = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUIZ!");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblLogoQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/quizLogo.png"))); // NOI18N
        lblLogoQuiz.setMaximumSize(new java.awt.Dimension(920, 460));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContraseña.setText("Contraseña:");

        lblAunNoTieneCuenta.setText("Aun no tiene cuenta?");

        lblRegistrarse.setBackground(new java.awt.Color(0, 0, 0));
        lblRegistrarse.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        lblRegistrarse.setForeground(new java.awt.Color(255, 204, 0));
        lblRegistrarse.setText("Registrarse");
        lblRegistrarse.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lblRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseClicked(evt);
            }
        });

        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lblLogoQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnIniciarSesion))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblContraseña)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblWarning)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblAunNoTieneCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRegistrarse))
                            .addComponent(txtUsuario)
                            .addComponent(txtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblLogoQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lblWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnIniciarSesion)
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAunNoTieneCuenta)
                    .addComponent(lblRegistrarse))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
       
        if (!txtUsuario.getText().isEmpty() && !txtContrasena.getText().isEmpty()) {
            
            UsuarioDto usuarioDto = new UsuarioControl().
                    IniciarSesion(txtUsuario.getText(), txtContrasena.getText());
            
            if (usuarioDto != null) {
                
                try {
                    
                    if (Class.forName("modelo.transferobject.AdminDto").isInstance(usuarioDto)) {
                        
                        infoAdmin = (AdminDto) usuarioDto;
                        txtUsuario.setText("");
                        txtContrasena.setText("");
                        
                        this.dispose();
                        FuncionesAdmin funcionesAdmin = new FuncionesAdmin();
                        funcionesAdmin.setVisible(rootPaneCheckingEnabled);
                        
                    } else if (Class.forName("modelo.transferobject.JugadorDto").isInstance(usuarioDto)) {
                        
                        infoJugador = (JugadorDto) usuarioDto;
                        txtUsuario.setText("");
                        txtContrasena.setText("");
                        
                        this.dispose();
                        Juego juego = new Juego();
                        juego.setVisible(true);
                        
                    }
                    
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
                
            } else {
                lblWarning.setText("Usuario y/o contraseña incorrectos");
                txtUsuario.setText("");
                txtContrasena.setText("");
            }
            
        } else {
            
            lblWarning.setText("Por favor, rellene todos los campos");
        }
        
       

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void lblRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseClicked
        
        this.dispose();
        Registro registrar = new Registro();
        registrar.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_lblRegistrarseMouseClicked

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    public static JugadorDto getInfoJugador() {
        return infoJugador;
    }

    public static void setInfoJugador(JugadorDto infoJugador) {
        Principal.infoJugador = infoJugador;
    }

    public static AdminDto getInfoAdmin() {
        return infoAdmin;
    }

    public static void setInfoAdmin(AdminDto infoAdmin) {
        Principal.infoAdmin = infoAdmin;
    }

    //Getter & Setter
    
    

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JLabel lblAunNoTieneCuenta;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblLogoQuiz;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
